import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";

import Footer from "@/components/Footer";


const openSans = Open_Sans({ 
  weight:['300','400','500','600','700','800'],
  subsets: ["latin"] });

export const metadata: Metadata = {
  icons:'/favicon.ico',
  title: "KOLDWARE INDUSTRIES",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={openSans.className}>
      
        {children}
     <Footer/>
      </body>
    </html>
  );
}
